### PR TITLE
Add SlideSwitch

### PR DESCRIPTION
**Pull request by Leaking**

### CODE REVIEW

**Comment by jact-hz** [comment]
您好,首先感谢您的开源组件android-auto-scroll-view-pager对我项目的帮助。
我在使用过程遇到一点问题。
我在https://github.com/chrisbanes/Android-PullToRefresh
的scrollview中嵌套了android-auto-scroll-view-pager
但是图片的上下滑动不能触发scrollview。是否有解决方法？
谢谢了。

在 2015-03-11 22:00:55，"Trinea" <notifications@github.com> 写道：


Merged #110.

**Comment by lsjwzh** [comment]
继承 PullToRefreshListView 然后再dispatchTouchEvent处判断是否在ViewPager区域中。即可

**Comment by lsjwzh** [comment]
/**
 * 用于截获dispatchTouchEvent事件
 * Created by Administrator on 13-9-30.
 */
public class PullToRefreshListViewExtend extends PullToRefreshListView {


    public interface OnDispatchTouchEventListener {
        public boolean dispatchTouchEvent(MotionEvent event);
    }

    private OnDispatchTouchEventListener onDispatchTouchEventListener;

    public PullToRefreshListViewExtend(Context context) {
        super(context);
    }

    public PullToRefreshListViewExtend(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public PullToRefreshListViewExtend(Context context, Mode mode) {
        super(context, mode);
    }

    public PullToRefreshListViewExtend(Context context, Mode mode, AnimationStyle style) {
        super(context, mode, style);
    }


    @Override
    public boolean dispatchTouchEvent(MotionEvent event) {
        try {
            if (getOnDispatchTouchEventListener() != null
                    && getOnDispatchTouchEventListener().dispatchTouchEvent(event)) {
                return true;
            }
            return super.dispatchTouchEvent(event);
        } catch (IllegalArgumentException e) {
            //catch   java.lang.IllegalArgumentException: pointerIndex out of range
            return true;
        }
    }

    public OnDispatchTouchEventListener getOnDispatchTouchEventListener() {
        return onDispatchTouchEventListener;
    }

    public void setOnDispatchTouchEventListener(OnDispatchTouchEventListener onDispatchTouchEventListener) {
        this.onDispatchTouchEventListener = onDispatchTouchEventListener;
    }

}

**Comment by lsjwzh** [comment]
private class OnDispatchTouchEventListener implements
            PullToRefreshScrollViewExtend.OnDispatchTouchEventListener {
        boolean mActionDownOnBannerArea;

        @Override
        public boolean dispatchTouchEvent(MotionEvent event) {
            boolean inBannerArea = isInBannerArea(event);
            if ((event.getAction() == MotionEvent.ACTION_DOWN
                    && inBannerArea) || mActionDownOnBannerArea) {
                //如果在banner区域按下，则开始触发bannerViewPager的ontouch事件
                mActionDownOnBannerArea = true;
                try {
                    mBannerViews.bannerViewPager.onTouchEvent(event);
                } catch (IllegalStateException e) {

                }
            }
            if (event.getAction() == MotionEvent.ACTION_UP) {
                mActionDownOnBannerArea = false;
                mBannerViews.bannerViewPager.startAutoScroll();
            }
            return false;
        }
    }

**Comment by lsjwzh** [comment]
使用的时候：        
‘mPTRScrollView.setOnDispatchTouchEventListener(new OnDispatchTouchEventListener());’

**Comment by jact-hz** [comment]
isInBannerArea(event)和mBannerViews.bannerViewPager 找不到？

**Comment by Trinea** [comment]
相关问题请大家到 https://github.com/android-cn/interview-questions 下面新建 Issue 讨论，谢谢，这里讨论会影响太多人。

**Pull request merged**
